{{- if .Values.postgres.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "global.postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.postgres.service.port }}
      from:
        - podSelector:
            matchLabels:
              {{- include "server.selectorLabels" . | nindent 14 }}
  policyTypes:
    - Ingress
{{- end }}
