apiVersion: v2
name: didwebvh-server-py
icon: https://identity.foundation/didwebvh/didwebvh.jpg
description: An api server to register and serve web dids with verifiable history.
type: application
version: 0.3.2
appVersion: 0.3.2

maintainers:
  - name: PatStLouis
    email: patrick.st-louis@opsecid.ca
    url: https://github.com/PatStLouis

dependencies:
  - name: postgresql
    version: 11.9.13
    repository: https://charts.bitnami.com/bitnami/
    condition: postgresql.enabled
  - name: common
    version: 2.x.x
    repository: https://charts.bitnami.com/bitnami/
    tags:
      - bitnami-common
