apiVersion: v2
name: didwebvh-server-py
icon: https://identity.foundation/didwebvh/didwebvh.jpg
description: An api server to register and serve web dids with verifiable history.
type: application
version: 0.7.0
appVersion: 0.5.0

maintainers:
  - name: PatStLouis
    email: patrick.st-louis@opsecid.ca
    url: https://github.com/PatStLouis

dependencies:
  - name: postgres
    version: "0.16.0"
    repository: oci://registry-1.docker.io/cloudpirates
    condition: postgres.enabled
